name: Publish NuGet Pkg
on:
  workflow_run:
    workflows: [ "SonarCloud" ]
    types:
      - completed
  create:
    branches:
      - release/**
jobs:
  Publish:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ChatbotProject.Common.sln'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
        
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: '5.x'
      - run: nuget restore ChatbotProject.Common.sln
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}}
