name: Publish NuGet Pkg
on:
  workflow_run:
    workflows: [ "SonarCloud" ]
  create:
    branches:
      - release/**
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: '5.x'
      - run: nuget restore ChatbotProject.Common.sln
